import type { GemColor } from "@repo/shared-types";

export type DevelopmentCardTier = 1 | 2 | 3;

export interface DevelopmentCardCatalogEntry {
  id: string;
  tier: DevelopmentCardTier;
  bonus: GemColor;
  points: number;
  cost: Record<GemColor, number>;
}

// Source: Splendor base-game card table (physical fixed deck, 90 cards)
// mirrored at:
// https://docs.google.com/spreadsheets/d/15ghp8rJ_vdVgxZIVJGawAYQXRMZSVHJYpZRfQUplAhE
export const DEVELOPMENT_CARDS: readonly DevelopmentCardCatalogEntry[] = [
  {
    id: "t1-01",
    tier: 1,
    bonus: "onyx",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 1,
      emerald: 1,
      ruby: 1,
      onyx: 0,
    },
  },
  {
    id: "t1-02",
    tier: 1,
    bonus: "onyx",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 2,
      emerald: 1,
      ruby: 1,
      onyx: 0,
    },
  },
  {
    id: "t1-03",
    tier: 1,
    bonus: "onyx",
    points: 0,
    cost: {
      diamond: 2,
      sapphire: 2,
      emerald: 0,
      ruby: 1,
      onyx: 0,
    },
  },
  {
    id: "t1-04",
    tier: 1,
    bonus: "onyx",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 1,
      ruby: 3,
      onyx: 1,
    },
  },
  {
    id: "t1-05",
    tier: 1,
    bonus: "onyx",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 2,
      ruby: 1,
      onyx: 0,
    },
  },
  {
    id: "t1-06",
    tier: 1,
    bonus: "onyx",
    points: 0,
    cost: {
      diamond: 2,
      sapphire: 0,
      emerald: 2,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-07",
    tier: 1,
    bonus: "onyx",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 3,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-08",
    tier: 1,
    bonus: "onyx",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 4,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-09",
    tier: 1,
    bonus: "sapphire",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 0,
      emerald: 1,
      ruby: 1,
      onyx: 1,
    },
  },
  {
    id: "t1-10",
    tier: 1,
    bonus: "sapphire",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 0,
      emerald: 1,
      ruby: 2,
      onyx: 1,
    },
  },
  {
    id: "t1-11",
    tier: 1,
    bonus: "sapphire",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 0,
      emerald: 2,
      ruby: 2,
      onyx: 0,
    },
  },
  {
    id: "t1-12",
    tier: 1,
    bonus: "sapphire",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 1,
      emerald: 3,
      ruby: 1,
      onyx: 0,
    },
  },
  {
    id: "t1-13",
    tier: 1,
    bonus: "sapphire",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 2,
    },
  },
  {
    id: "t1-14",
    tier: 1,
    bonus: "sapphire",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 2,
      ruby: 0,
      onyx: 2,
    },
  },
  {
    id: "t1-15",
    tier: 1,
    bonus: "sapphire",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 3,
    },
  },
  {
    id: "t1-16",
    tier: 1,
    bonus: "sapphire",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 4,
      onyx: 0,
    },
  },
  {
    id: "t1-17",
    tier: 1,
    bonus: "diamond",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 1,
      emerald: 1,
      ruby: 1,
      onyx: 1,
    },
  },
  {
    id: "t1-18",
    tier: 1,
    bonus: "diamond",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 1,
      emerald: 2,
      ruby: 1,
      onyx: 1,
    },
  },
  {
    id: "t1-19",
    tier: 1,
    bonus: "diamond",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 2,
      emerald: 2,
      ruby: 0,
      onyx: 1,
    },
  },
  {
    id: "t1-20",
    tier: 1,
    bonus: "diamond",
    points: 0,
    cost: {
      diamond: 3,
      sapphire: 1,
      emerald: 0,
      ruby: 0,
      onyx: 1,
    },
  },
  {
    id: "t1-21",
    tier: 1,
    bonus: "diamond",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 2,
      onyx: 1,
    },
  },
  {
    id: "t1-22",
    tier: 1,
    bonus: "diamond",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 2,
      emerald: 0,
      ruby: 0,
      onyx: 2,
    },
  },
  {
    id: "t1-23",
    tier: 1,
    bonus: "diamond",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 3,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-24",
    tier: 1,
    bonus: "diamond",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 4,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-25",
    tier: 1,
    bonus: "emerald",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 1,
      emerald: 0,
      ruby: 1,
      onyx: 1,
    },
  },
  {
    id: "t1-26",
    tier: 1,
    bonus: "emerald",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 1,
      emerald: 0,
      ruby: 1,
      onyx: 2,
    },
  },
  {
    id: "t1-27",
    tier: 1,
    bonus: "emerald",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 1,
      emerald: 0,
      ruby: 2,
      onyx: 2,
    },
  },
  {
    id: "t1-28",
    tier: 1,
    bonus: "emerald",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 3,
      emerald: 1,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-29",
    tier: 1,
    bonus: "emerald",
    points: 0,
    cost: {
      diamond: 2,
      sapphire: 1,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-30",
    tier: 1,
    bonus: "emerald",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 2,
      emerald: 0,
      ruby: 2,
      onyx: 0,
    },
  },
  {
    id: "t1-31",
    tier: 1,
    bonus: "emerald",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 3,
      onyx: 0,
    },
  },
  {
    id: "t1-32",
    tier: 1,
    bonus: "emerald",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 4,
    },
  },
  {
    id: "t1-33",
    tier: 1,
    bonus: "ruby",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 1,
      emerald: 1,
      ruby: 0,
      onyx: 1,
    },
  },
  {
    id: "t1-34",
    tier: 1,
    bonus: "ruby",
    points: 0,
    cost: {
      diamond: 2,
      sapphire: 1,
      emerald: 1,
      ruby: 0,
      onyx: 1,
    },
  },
  {
    id: "t1-35",
    tier: 1,
    bonus: "ruby",
    points: 0,
    cost: {
      diamond: 2,
      sapphire: 0,
      emerald: 1,
      ruby: 0,
      onyx: 2,
    },
  },
  {
    id: "t1-36",
    tier: 1,
    bonus: "ruby",
    points: 0,
    cost: {
      diamond: 1,
      sapphire: 0,
      emerald: 0,
      ruby: 1,
      onyx: 3,
    },
  },
  {
    id: "t1-37",
    tier: 1,
    bonus: "ruby",
    points: 0,
    cost: {
      diamond: 0,
      sapphire: 2,
      emerald: 1,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-38",
    tier: 1,
    bonus: "ruby",
    points: 0,
    cost: {
      diamond: 2,
      sapphire: 0,
      emerald: 0,
      ruby: 2,
      onyx: 0,
    },
  },
  {
    id: "t1-39",
    tier: 1,
    bonus: "ruby",
    points: 0,
    cost: {
      diamond: 3,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t1-40",
    tier: 1,
    bonus: "ruby",
    points: 1,
    cost: {
      diamond: 4,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-01",
    tier: 2,
    bonus: "onyx",
    points: 1,
    cost: {
      diamond: 3,
      sapphire: 2,
      emerald: 2,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-02",
    tier: 2,
    bonus: "onyx",
    points: 1,
    cost: {
      diamond: 3,
      sapphire: 0,
      emerald: 3,
      ruby: 0,
      onyx: 2,
    },
  },
  {
    id: "t2-03",
    tier: 2,
    bonus: "onyx",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 1,
      emerald: 4,
      ruby: 2,
      onyx: 0,
    },
  },
  {
    id: "t2-04",
    tier: 2,
    bonus: "onyx",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 5,
      ruby: 3,
      onyx: 0,
    },
  },
  {
    id: "t2-05",
    tier: 2,
    bonus: "onyx",
    points: 2,
    cost: {
      diamond: 5,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-06",
    tier: 2,
    bonus: "onyx",
    points: 3,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 6,
    },
  },
  {
    id: "t2-07",
    tier: 2,
    bonus: "sapphire",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 2,
      emerald: 2,
      ruby: 3,
      onyx: 0,
    },
  },
  {
    id: "t2-08",
    tier: 2,
    bonus: "sapphire",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 2,
      emerald: 3,
      ruby: 0,
      onyx: 3,
    },
  },
  {
    id: "t2-09",
    tier: 2,
    bonus: "sapphire",
    points: 2,
    cost: {
      diamond: 5,
      sapphire: 3,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-10",
    tier: 2,
    bonus: "sapphire",
    points: 2,
    cost: {
      diamond: 2,
      sapphire: 0,
      emerald: 0,
      ruby: 1,
      onyx: 4,
    },
  },
  {
    id: "t2-11",
    tier: 2,
    bonus: "sapphire",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 5,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-12",
    tier: 2,
    bonus: "sapphire",
    points: 3,
    cost: {
      diamond: 0,
      sapphire: 6,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-13",
    tier: 2,
    bonus: "diamond",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 3,
      ruby: 2,
      onyx: 2,
    },
  },
  {
    id: "t2-14",
    tier: 2,
    bonus: "diamond",
    points: 1,
    cost: {
      diamond: 2,
      sapphire: 3,
      emerald: 0,
      ruby: 3,
      onyx: 0,
    },
  },
  {
    id: "t2-15",
    tier: 2,
    bonus: "diamond",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 1,
      ruby: 4,
      onyx: 2,
    },
  },
  {
    id: "t2-16",
    tier: 2,
    bonus: "diamond",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 5,
      onyx: 3,
    },
  },
  {
    id: "t2-17",
    tier: 2,
    bonus: "diamond",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 5,
      onyx: 0,
    },
  },
  {
    id: "t2-18",
    tier: 2,
    bonus: "diamond",
    points: 3,
    cost: {
      diamond: 6,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-19",
    tier: 2,
    bonus: "emerald",
    points: 1,
    cost: {
      diamond: 3,
      sapphire: 0,
      emerald: 2,
      ruby: 3,
      onyx: 0,
    },
  },
  {
    id: "t2-20",
    tier: 2,
    bonus: "emerald",
    points: 1,
    cost: {
      diamond: 2,
      sapphire: 3,
      emerald: 0,
      ruby: 0,
      onyx: 2,
    },
  },
  {
    id: "t2-21",
    tier: 2,
    bonus: "emerald",
    points: 2,
    cost: {
      diamond: 4,
      sapphire: 2,
      emerald: 0,
      ruby: 0,
      onyx: 1,
    },
  },
  {
    id: "t2-22",
    tier: 2,
    bonus: "emerald",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 5,
      emerald: 3,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-23",
    tier: 2,
    bonus: "emerald",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 5,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-24",
    tier: 2,
    bonus: "emerald",
    points: 3,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 6,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-25",
    tier: 2,
    bonus: "ruby",
    points: 1,
    cost: {
      diamond: 2,
      sapphire: 0,
      emerald: 0,
      ruby: 2,
      onyx: 3,
    },
  },
  {
    id: "t2-26",
    tier: 2,
    bonus: "ruby",
    points: 1,
    cost: {
      diamond: 0,
      sapphire: 3,
      emerald: 0,
      ruby: 2,
      onyx: 3,
    },
  },
  {
    id: "t2-27",
    tier: 2,
    bonus: "ruby",
    points: 2,
    cost: {
      diamond: 1,
      sapphire: 4,
      emerald: 2,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t2-28",
    tier: 2,
    bonus: "ruby",
    points: 2,
    cost: {
      diamond: 3,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 5,
    },
  },
  {
    id: "t2-29",
    tier: 2,
    bonus: "ruby",
    points: 2,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 5,
    },
  },
  {
    id: "t2-30",
    tier: 2,
    bonus: "ruby",
    points: 3,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 6,
      onyx: 0,
    },
  },
  {
    id: "t3-01",
    tier: 3,
    bonus: "onyx",
    points: 3,
    cost: {
      diamond: 3,
      sapphire: 3,
      emerald: 5,
      ruby: 3,
      onyx: 0,
    },
  },
  {
    id: "t3-02",
    tier: 3,
    bonus: "onyx",
    points: 4,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 7,
      onyx: 0,
    },
  },
  {
    id: "t3-03",
    tier: 3,
    bonus: "onyx",
    points: 4,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 3,
      ruby: 6,
      onyx: 3,
    },
  },
  {
    id: "t3-04",
    tier: 3,
    bonus: "onyx",
    points: 5,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 7,
      onyx: 3,
    },
  },
  {
    id: "t3-05",
    tier: 3,
    bonus: "sapphire",
    points: 3,
    cost: {
      diamond: 3,
      sapphire: 0,
      emerald: 3,
      ruby: 3,
      onyx: 5,
    },
  },
  {
    id: "t3-06",
    tier: 3,
    bonus: "sapphire",
    points: 4,
    cost: {
      diamond: 7,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t3-07",
    tier: 3,
    bonus: "sapphire",
    points: 4,
    cost: {
      diamond: 6,
      sapphire: 3,
      emerald: 0,
      ruby: 0,
      onyx: 3,
    },
  },
  {
    id: "t3-08",
    tier: 3,
    bonus: "sapphire",
    points: 5,
    cost: {
      diamond: 7,
      sapphire: 3,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t3-09",
    tier: 3,
    bonus: "diamond",
    points: 3,
    cost: {
      diamond: 0,
      sapphire: 3,
      emerald: 3,
      ruby: 5,
      onyx: 3,
    },
  },
  {
    id: "t3-10",
    tier: 3,
    bonus: "diamond",
    points: 4,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 7,
    },
  },
  {
    id: "t3-11",
    tier: 3,
    bonus: "diamond",
    points: 4,
    cost: {
      diamond: 3,
      sapphire: 0,
      emerald: 0,
      ruby: 3,
      onyx: 6,
    },
  },
  {
    id: "t3-12",
    tier: 3,
    bonus: "diamond",
    points: 5,
    cost: {
      diamond: 3,
      sapphire: 0,
      emerald: 0,
      ruby: 0,
      onyx: 7,
    },
  },
  {
    id: "t3-13",
    tier: 3,
    bonus: "emerald",
    points: 3,
    cost: {
      diamond: 5,
      sapphire: 3,
      emerald: 0,
      ruby: 3,
      onyx: 3,
    },
  },
  {
    id: "t3-14",
    tier: 3,
    bonus: "emerald",
    points: 4,
    cost: {
      diamond: 0,
      sapphire: 7,
      emerald: 0,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t3-15",
    tier: 3,
    bonus: "emerald",
    points: 4,
    cost: {
      diamond: 3,
      sapphire: 6,
      emerald: 3,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t3-16",
    tier: 3,
    bonus: "emerald",
    points: 5,
    cost: {
      diamond: 0,
      sapphire: 7,
      emerald: 3,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t3-17",
    tier: 3,
    bonus: "ruby",
    points: 3,
    cost: {
      diamond: 3,
      sapphire: 5,
      emerald: 3,
      ruby: 0,
      onyx: 3,
    },
  },
  {
    id: "t3-18",
    tier: 3,
    bonus: "ruby",
    points: 4,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 7,
      ruby: 0,
      onyx: 0,
    },
  },
  {
    id: "t3-19",
    tier: 3,
    bonus: "ruby",
    points: 4,
    cost: {
      diamond: 0,
      sapphire: 3,
      emerald: 6,
      ruby: 3,
      onyx: 0,
    },
  },
  {
    id: "t3-20",
    tier: 3,
    bonus: "ruby",
    points: 5,
    cost: {
      diamond: 0,
      sapphire: 0,
      emerald: 7,
      ruby: 3,
      onyx: 0,
    },
  },
];

export const DEVELOPMENT_CARD_COUNT_BY_TIER: Readonly<Record<DevelopmentCardTier, number>> = {
  1: 40,
  2: 30,
  3: 20,
};

export function getCardsByTier(tier: DevelopmentCardTier): readonly DevelopmentCardCatalogEntry[] {
  return DEVELOPMENT_CARDS.filter((card) => card.tier === tier);
}
